NetworkName: wg-network

device1:
    Address: 10.1.1.1
    AllowedIPs: 10.1.1.0/24  # always-on relay/bouncer for the whole network
    Endpoint: my.publicip.com
    ListenPort: 51821 # port-forwarding enabled on router

device2:
    Address: 10.1.1.2
    Endpoint: my.publicip.com
    ListenPort: 51822 # port-forwarding enabled on router

device3:
    Address: 10.1.1.3
    Endpoint: my.publicip.com
    ListenPort: 51823 # port-forwarding enabled on router

device4:
    Address: 10.1.1.4
    Endpoint: my.publicip.com
    ListenPort: 51824 # port-forwarding enabled on router

device5: # behind no-access router/NAT on another network
    Address: 10.1.1.5
    PersistentKeepalive: 25

device6: # behind no-access router/NAT on another network
    Address: 10.1.1.6
    PersistentKeepalive: 25

device7: # mobile - no fixed IP
    Address: 10.1.1.7
    PersistentKeepalive: 25

device8: # mobile - no fixed IP
    Address: 10.1.1.8
    PersistentKeepalive: 25
